In [1]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
#Cargar archivo csv desde seaborn
from google.colab import files 
files.upload()

In [3]:
#Carga desde un archivo .xlsx sin indice 
data= pd.read_excel('microretailer_mit_lift_lab_actualizado.xlsx')

In [23]:
#analizamos caso 1 de correlación entre variable de número de clientes en la tienda respecto al número de estantes en la tienda, el número de refrigeradores y el número de empleados permanentes
Vars_Indep= data[['268_number_fridges','104_how_many_shelves_does_the_micro_retailer_have', '2_current_permanent_employees']]
Var_Dep= data['97_number_of_customers_in_store']

In [24]:
#se define modelo como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [25]:
#Verificamos la función relacionada al modelo 
type(model)

sklearn.linear_model._base.LinearRegression

In [26]:
#ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)

LinearRegression()

In [27]:
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'normalize': 'deprecated',
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['268_number_fridges',
        '104_how_many_shelves_does_the_micro_retailer_have',
        '2_current_permanent_employees'], dtype=object),
 'n_features_in_': 3,
 'coef_': array([0.19590676, 0.0080384 , 0.08928311]),
 '_residues': 972.3842620033486,
 'rank_': 3,
 'singular_': array([260.78872511,  58.823247  ,  42.76081943]),
 'intercept_': 0.8414396869333318}

In [28]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R determinado
model.score(Vars_Indep,Var_Dep)

0.1130725423688903

In [29]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep= data[['268_number_fridges','104_how_many_shelves_does_the_micro_retailer_have', '2_current_permanent_employees']]
Var_Dep= data['97_number_of_customers_in_store']

In [30]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [31]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [32]:
#Se escalan todos los datos
escalar= StandardScaler()

In [33]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [34]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [35]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [36]:
#Realizamos una predicción
y_pred= algoritmo.predict(X_test)
y_pred 

array([0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [37]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[43  0  0  1  0  0  0]
 [18  0  1  0  0  0  0]
 [16  0  2  1  0  0  0]
 [ 6  1  1  1  0  0  0]
 [ 4  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0]]


In [38]:
#Calculo la precisión del modelo 
from sklearn.metrics import precision_score
precision= precision_score(y_test, y_pred, average="micro", pos_label="yes")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.46464646464646464


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


In [39]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud= accuracy_score(y_test, y_pred)
print('Exactitud del modelo')
print(exactitud)

Exactitud del modelo
0.46464646464646464


In [40]:
#Calculo la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test, y_pred, average='micro', pos_label="yes")
print('Sensibilidad del modelo')
print(sensibilidad)

Sensibilidad del modelo
0.46464646464646464


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


In [41]:
#3y4
#analizamos caso 1 de correlación entre variable de número de clientes en la tienda respecto al número de estantes en la tienda, el número de refrigeradores y el número de empleados permanentes
Vars_Indep= data[['145_number_direct_competitors','272_card_days_receive_money', '4_number_permanent_employees_last_year']]
Var_Dep= data['97_number_of_customers_in_store']

In [42]:
#se define modelo como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [ ]:
#Verificamos la función relacionada al modelo 
type(model)

In [44]:
#ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)

LinearRegression()

In [45]:
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'normalize': 'deprecated',
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['145_number_direct_competitors', '272_card_days_receive_money',
        '4_number_permanent_employees_last_year'], dtype=object),
 'n_features_in_': 3,
 'coef_': array([-0.00533727,  0.00910135,  0.07015527]),
 '_residues': 1064.029636800752,
 'rank_': 3,
 'singular_': array([81.80139886, 76.41805793, 13.55424753]),
 'intercept_': 1.2471934335937875}

In [46]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R determinado
model.score(Vars_Indep,Var_Dep)

0.029481309510751674

In [48]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep= data[['145_number_direct_competitors','272_card_days_receive_money', '4_number_permanent_employees_last_year']]
Var_Dep= data['97_number_of_customers_in_store']

In [49]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [50]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [51]:
#Se escalan todos los datos
escalar= StandardScaler()

In [52]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [53]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [54]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Realizamos una predicción
y_pred= algoritmo.predict(X_test)
y_pred 

In [56]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[38  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0]
 [22  1  0  0  0  0  0  0]
 [10  1  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0]]


In [57]:
#Calculo la precisión del modelo 
from sklearn.metrics import precision_score
precision= precision_score(y_test, y_pred, average="micro", pos_label="yes")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.3838383838383838


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


In [58]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud= accuracy_score(y_test, y_pred)
print('Exactitud del modelo')
print(exactitud)

Exactitud del modelo
0.3838383838383838


In [59]:
#Calculo la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test, y_pred, average='micro', pos_label="yes")
print('Sensibilidad del modelo')
print(sensibilidad)

Sensibilidad del modelo
0.3838383838383838


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
